### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by srilaxmipillalamarri** [linhtch90/microservices-java-demo-zoo-devto#1]

**Comment by zad999** [comment]
i get this error when i run my code :
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at kerberos.cryptotechniques.EncryptorDecryptor.decrypt(EncryptorDecryptor.java:112)
	at kerberos.client.Client.parseResponseFromAuthenticationServer(Client.java:186)
	at kerberos.client.Client.main(Client.java:82)
C:\Users\elathir\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\elathir\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:68: Java returned: 1
